### ISSUE TITLE
3-1-81 → YY-M-D

### ISSUE THREAD

**Issue by onecreative** [gr2m/moment.parseFormat#12]
`moment.parseFormat('3-1-81')` parsed to `YY-M-D`, I expected: `M-D-YY`

Looks like this is still a problem. I checked 9-17-80, and it worked, but I'm guessing that was because of the 17.

**Comment by gr2m** [comment]
Fixed via https://github.com/gr2m/moment.parseFormat/commit/5d3230648c41933075d34b49f3ad4c9eed342223

It now parses to `D-M-YY`. If you prefer the `Month-Day-Year` order, pass `{preferredOrder: 'MDY'}`
