### ISSUE TITLE
01-01-2015 → YYYY-MM-DD

### ISSUE THREAD

**Issue by rdietrick** [gr2m/moment.parseFormat#15]
`moment.parseFormat('01-01-2015')` parsed to `YYYY-MM-DD`, I expected: `MM-DD-YYYY`

**Comment by gr2m** [comment]
wow, what a bad bug, thanks for reporting! I'll look into it

**Comment by gr2m** [comment]
You can use "/" as a separater instead of "-". That'll work

**Comment by gr2m** [comment]
fixed via https://github.com/gr2m/moment.parseFormat/commit/5d3230648c41933075d34b49f3ad4c9eed342223

**Comment by gr2m** [comment]
Sorry, forgot to mention, it now parses to `DD-MM-YYYY` per default, if you prefer Month first, pass `{preferredOrder: 'MDY'}`
