### ISSUE TITLE
10/8/2014 5:08:35 PM → M/D/YYYY h:mm:ss a

### ISSUE THREAD

**Issue by harsimranb** [gr2m/moment.parseFormat#20]
`moment.parseFormat('10/8/2014 5:08:35 PM')` parsed to `M/D/YYYY h:mm:ss a`, I expected: `M/D/YYYY h:mm:ss A`

**Comment by gr2m** [comment]
good catch! Wanna send a pull request?

**Comment by harsimranb** [comment]
Sure, I'll check it out at home.

**Comment by gr2m** [comment]
:+1:

**Comment by gr2m** [comment]
https://github.com/gr2m/moment.parseFormat/commit/bd9a73d0a8cc9a297aa870fe44550f03e76e5467
