### ISSUE TITLE
Error when trying to get format for "05/07/2015 12:20:15 UTC"

### ISSUE THREAD

**Issue by darlesson** [gr2m/moment.parseFormat#22]
format.replace(regexFillingWords, '[$1]'))

format.replace is not a function.

**Comment by gr2m** [comment]
`05/07/2015 12:20:15 UTC` gets parsed to `MM/DD/YYYY H:mm:ss UTC` which looks good to me?
No idea what `format.replace` is :)

**Comment by darlesson** [comment]
Reviewing the errors I was getting, the correct message is "TypeError: 'undefined' is not a function (evaluating 'replaceEndian.bind(null, options)')".

I am using QUnit and running PhantomJS to test proper date format. What happens is that PhantomJS doesn't have Function.prototype.bind.

**Comment by gr2m** [comment]
Yes, that is a known PhantomJS but though. You have to add a .bind polyfill, or use PhantomJS 2.0

**Comment by gr2m** [comment]
s/but/bug

**Comment by darlesson** [comment]
I added an extension for bind. I will close as is.
