### ISSUE TITLE
Return failure when encountering unknown format

### ISSUE THREAD

**Issue by theazureshadow** [gr2m/moment.parseFormat#9]
If I use `moment.parseFormat('yesterday')`, I get a format of `'yesterday'`. I'd rather be able to tell that parseFormat didn't recognize the format, for example by returning `undefined`.

**Comment by theazureshadow** [comment]
My use case is to validate that a date entered by the user contains enough pieces to accurately identify a day (e.g. has day and month with implied year, or has day, month, and year), and isn't just a random string they entered, like `"I want 20 October apples"`.

A boolean might not give enough information for some validations like this. Another option would be to provide a second parse method that which shows what parts of the input were calculated as a date:

    moment.parseFormat.parseToArray("yesterday")
    // returns [], since nothing could be converted to a format string

    moment.parseFormat.parseToArray("8th January 1986")
    // returns [
      {pos:0, len:3, fmt: "Do"},
      {pos:4, len:7, fmt: "'MMMM"},
      {pos:12, len:4, fmt: "YYYY"}
    ]

A simpler option that would address my use case, (but not be quite as useful) would be to return a mask of the unconsumed input:

    moment.parseFormat.parseToMask("8th January 1986")
    // returns                     "                "
    moment.parseFormat.parseToMask("This is the 8th of May")
    // returns                     "This is the     of    "

**Comment by gr2m** [comment]
@theazureshadow would you like to try build the `parseToArray` method? We could either incorporate it into core, or if it becomes to big, make it an external file that'd you'd only load if you need the method?

**Comment by gr2m** [comment]
closing in favor of #9

**Comment by LarryBattle** [comment]
@gr2m meant #26
